services:
  - type: web
    name: nocapchicken
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements-app.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 "app:create_app()"
    envVars:
      - key: GOOGLE_PLACES_API_KEY
        sync: false        # set manually in Render dashboard
